---
- hosts: testlhi0.sportaculous.com
  remote_user: ubuntu
  sudo: yes
  vars:
    logstash_owner: root
    logstash_group: root
    logstash_dir: /opt/logstash2
    logstash_etcdir: /opt/logstash2/etc
    logstash_bindir: /opt/logstash2/bin
    logstash_patterndir: /opt/logstash2/pattern
  tasks:
  - name: "Create logstash Directory :: {{ logstash_dir }}"
    file: path={{ logstash_dir }} owner=root group=root state=directory
    sudo: True
  
  - name: Create logstash Configuration Directory {{ logstash_etcdir }}
    file: path={{ logstash_etcdir }} owner=root group=root state=directory
    sudo: True
  
  - name: Create logstash Binary Directory {{ logstash_bindir }}
    file: path={{ logstash_bindir }} owner=root group=root state=directory
    sudo: True
  
  - name: Create logstash Pattern Directory {{ logstash_patterndir }}
    file: path={{ logstash_patterndir }} owner=root group=root state=directory
    sudo: True
 
  #- name: download logstash-1.3.2-flatjar.jar
  #  get_url: url=https://s3-eu-west-1.amazonaws.com/binary.sportaculous.com/logstash-1.3.2-flatjar.jar dest=/opt/logstash/bin/logstash-1.3.2-flatjar.jar mode=0644 
  #
  #- name: Copy config file to config dir
  #  copy: src=/etc/ansible/playbooks/logstash/files/logstash-syslog.conf dest=/opt/logstash/etc/logstash-syslog.conf owner=root group=root mode=0644
  #  notify: restart logstash

  #- name: Copy launch script to binary dir
  #  copy: src=/etc/ansible/playbooks/logstash/files/run.sh dest=/opt/logstash/bin/run.sh owner=root group=root mode=0755
  #  notify: restart logstash

  #- name: Create init file
  #  copy: src=/etc/ansible/playbooks/logstash/files/logstash-init-script dest=/etc/init.d/logstash owner=root group=root mode=0755
  #  notify: restart logstash

  - name: ensure running
    service: name=logstash state=running

  handlers:
  - name: restart logstash
    service: name=logstash state=running
