FROM  sportaculous/java-base

# Install SFTP Server
RUN mkdir /sporta
RUN wget https://s3-eu-west-1.amazonaws.com/releases.sportaculous.com/sportaculous-upload-sftp-server-application-production-0.39.0.tar.gz
RUN tar xvzf sportaculous-upload-sftp-server-application-production-0.39.0.tar.gz -C /sporta

# Expose mongodb port
EXPOSE 443

WORKDIR /sporta/bin/linux64/
# Launch mongodb
ENTRYPOINT ["sh" ,"run.sh", "run"]
